# Generated by Django 2.2.7 on 2019-12-02 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import grader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=100)),
                ('submission_id', models.CharField(max_length=30)),
                ('source', models.FileField(upload_to=grader.models.path)),
                ('who', models.CharField(max_length=100)),
                ('when', models.DateTimeField(verbose_name='date submited')),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('pid', models.CharField(max_length=100)),
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('input', models.FileField(blank=True, null=True, upload_to=grader.models.path)),
                ('output', models.FileField(blank=True, null=True, upload_to=grader.models.path)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=30, unique=True)),
                ('time_limit', models.CharField(max_length=100)),
                ('mem_limit', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
